
<div style="font-family: Arial,sans-serif;">
    <h1 style="font-size: 1.3em; color: white; background-color: #459436; margin: 0; padding: .5em .5em 1em .5em;">
        ##reservation.action##: ##reservation.item.name##
    </h1>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0">
    <div>
        <p>Olá, ##reservation.user##</p>
        <p>
            Esta é uma mensagem de alerta sobre a reserva <strong>##reservation.itemtype## (##reservation.item.name##)</strong>: 
            <em>##reservation.action##</em>.            
        </p>
        <p>Caso já tenha devolvido, ignore esta mensagem.</p>
        <hr>
        <p>
            <strong style="color: #459436; text-decoration: underline;">##lang.reservation.begin##:</strong>
            ##reservation.begin##
        </p>
        <p>
            <strong style="color: #459436; text-decoration: underline;">##lang.reservation.end##:</strong>
            ##reservation.end##
        </p>        
        
        ##IFreservation.tech##
        <p>
            <strong style="color: #459436; text-decoration: underline;">##lang.reservation.tech##:</strong>
            ##reservation.tech##
        </p>        
        ##ENDIFreservation.tech##
        <p>
            <strong style="color: #459436; text-decoration: underline;">##lang.reservation.comment##:</strong> 
            ##reservation.comment##
        </p>        
    </div>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0">
</div>
