<div style="font-family: Arial,sans-serif;">
    <h1 style="font-size: 1.3em; color: white; background-color: #459436; margin: 0; padding: .5em .5em 1em .5em;">[###ticket.id##] ##ticket.title##</h1>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" />
    
    <p>Olá, ##ticket.item.user##</p>
    <p>O chamado de número ####ticket.id## foi resolvido pela nossa equipe e as 
       informações do atendimento prestado podem ser acompanhadas em <a style="color: #459436;" href="##ticket.url##">##ticket.url##</a>.
    <p>
        Gostaríamos da sua avaliação a respeito deste atendimento. 
        Sua opinião é muito importante para aprimorarmos os nossos serviços.</p>
    <p>
        Convidamos você a participar da nossa pesquisa de satisfação disponível no link:
    </p>
    <p style="text-align: center">
        <a href="##ticket.urlsatisfaction##">##ticket.urlsatisfaction##</a>
    </p>
    <p>Agradecemos pelo seu contato e nos colocamos à disposição.</p>
</div>