<div style="font-family: Arial,sans-serif;">
    <h1 style="font-size: 1.3em; color: white; background-color: #459436; margin: 0; padding: .5em .5em 1em .5em;">[###ticket.id##] ##ticket.title##</h1>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" />
    
    <p>Olá, ##ticket.item.user##</p>
    <p>O chamado #<strong>##ticket.id##</strong> será analisado por <strong>##ticket.assigntousers##</strong>.</p>
    <p>
        Para adicionar um acompanhamento (ou informações adicionais), 
        você pode responder a esta mensagem (escrevendo acima ou abaixo da marcação indicada). 
        Para essa funcionalidade e outros detalhes do chamado,  
        <a href="##ticket.url##">acesse o sistema GLPI</a>.
    </p>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" /> 
    
    <div style="padding: 1.3em; margin: 3px 0 5px 0; border: 1px dashed black; font-size: 0.9em;">
        <p style="text-align: center"><strong><a style="color: #459436;" href="##ticket.url##">##ticket.title##</a></strong></p> 
        <hr>
        <div>##ticket.content##</div>
        <hr>
        <p><strong>##ticket.author##</strong></p>
    </div>
    
    
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" />
</div>