<div style="font-family: Arial,sans-serif;">
    <h1 style="font-size: 1.3em; color: white; background-color: #459436; margin: 0; padding: .5em .5em 1em .5em;">
        [##ticket.id##] ##ticket.title##
    </h1>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" />   
    <p>Esta é uma mensagem de atualização do <a href="##ticket.url##">chamado ###ticket.id##</a>: <em>##ticket.action##</em></p>
    <p><a href="##ticket.url##">Acesse o GLPI</a> para obter todos os detalhes.</p>
    <hr>
    <p>
        ##IFticket.category##
        <strong style="color: #459436;">##lang.ticket.category##</strong>:
        ##ticket.category## <br>
        ##ENDIFticket.category## 
        ##ELSEticket.category## 
        <strong style="color: red">##lang.ticket.nocategoryassigned##</strong><br>
        ##ENDELSEticket.category## 

        <strong style="color: #459436;">##lang.ticket.status##</strong>: 
            <span style="background-color: silver">&nbsp;##ticket.status##&nbsp;</span>
        <br>

        ##IFticket.assigntousers##
        <strong style="color: #459436;">Técnico responsável pelo chamado</strong>: 
            ##ticket.assigntousers## 
        <br>
        ##ENDIFticket.assigntousers##


        ##IFticket.assigntogroups## 
        <strong style="color: #459436;">##lang.ticket.assigntogroups##</strong>: 
            ##ticket.assigntogroups## 
        <br>
        ##ENDIFticket.assigntogroups##

        <strong style="color: #459436;">##lang.ticket.urgency##</strong>:
            ##ticket.urgency##
        <br>
        <strong style="color: #459436;">##lang.ticket.impact##</strong>: 
            ##ticket.impact##
        <br>
        <strong style="color: #459436;">##lang.ticket.priority##</strong>: 
            ##ticket.priority##    
    </p>
    <hr>
    <p><strong style="color: #459436;">Acompanhamentos (##ticket.numberoffollowups##)</strong></p>
    ##FOREACHfollowups## 
    <div style="min-height: 3em;padding: 1.3em; margin: 3px 0 5px 0; border: 1px dashed silver; font-size: 0.9em;margin-top: 1em">
        <div style="border-bottom: 1px solid silver ; padding-bottom: 1em; ">
            <strong>##followup.date##: ##followup.author##</strong> (##followup.requesttype##)
        </div>
        <div style="padding: 1em; ">
            ##followup.description##
        </div>    
    </div>
    ##ENDFOREACHfollowups##

    <hr>
    <p><strong style="color: #459436;">Tarefas (##ticket.numberoftasks##)</strong></p>
    ##FOREACHtasks## 
    <div style="min-height: 3em;padding: 1.3em; margin: 3px 0 5px 0; border: 1px dashed silver; font-size: 0.9em;margin-top: 1em">
        <div style="border-bottom: 1px solid silver ; padding-bottom: 1em; ">
            <strong>##task.author##</strong><br>##IFtask.begin## ##task.begin## - ##task.end## ##ENDIFtask.begin##
        </div>
        <div style="padding: 1em; ">
            ##task.description##
            <hr>
            <div style="text-align:center">##lang.task.status##: ##task.status##</div>
        </div>    
    </div>
    ##ENDFOREACHtasks##
    
    <hr>
    <p><strong style="color: #459436;">Itens relacionados</strong></p>
    <ol>
    <!-- ##FOREACHitems## ##IFticket.itemtype## -->
        <li>
                ##ticket.itemtype## 
                - ##ticket.item.name##
                ##IFticket.item.model## 
                    - ##lang.ticket.item.model##: 
                    ##ticket.item.model## 
                ##ENDIFticket.item.model##                 
                ##IFticket.item.serial## 
                    - ##lang.ticket.item.serial##: 
                    ##ticket.item.serial## 
                ##ENDIFticket.item.serial##                 
                ##IFticket.item.otherserial## 
                    - ##lang.ticket.item.otherserial##: 
                    ##ticket.item.otherserial## 
                ##ENDIFticket.item.otherserial##             
        </li>
    <!-- ##ENDIFticket.itemtype## ##ENDFOREACHitems## -->
    </ol>
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0; margin-top: 6em" /> 
    
    <div style="padding: 1.3em; margin: 3px 0 5px 0; border: 1px dashed black; font-size: 0.9em;">
        <p style="text-align: center"><strong><a style="color: #459436;" href="##ticket.url##">##ticket.title##</a></strong></p> 
        <hr>
        <div>##ticket.content##</div>
        <hr>
        <p><strong>##ticket.authors##</strong></p>
    </div>
    
    <hr style="background-color: #8ec547; min-height: 1.3em; border: 0; margin: 0;" />
</div>
